services:
  - type: web
    name: fastapi-service
    env: python
    buildCommand: ""
    startCommand: uvicorn api:app --host=0.0.0.0 --port=$PORT
    rootDir: api_app
    plan: free
    envVars:
      - key: PORT
        value: 10000

  - type: web
    name: streamlit-service
    env: python
    buildCommand: ""
    startCommand: sh setup.sh && streamlit run multiple_disease_pred.py
    rootDir: streamlit_app
    plan: free
    envVars:
      - key: PORT
        value: 10001
